
QHAL_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

CSRC += $(wildcard $(QHAL_DIR)/src/*.c)
EXTRAINCDIRS += $(QHAL_DIR)/include

CSRC += $(PLATFORMSRC)
CSRC += $(HALSRC)
CSRC += $(PORTSRC)
CSRC += $(KERNSRC)
CSRC += $(OSALSRC)
CSRC += $(STARTUPSRC)
CSRC += $(SHELLSRC)

ASRC += $(PLATFORMASM)
ASRC += $(HALASM)
ASRC += $(PORTASM)
ASRC += $(KERNASM)
ASRC += $(OSALASM)
ASRC += $(STARTUPASM)
ASRC += $(SHELLASM)

EXTRAINCDIRS += $(PLATFORMINC)
EXTRAINCDIRS += $(HALINC)
EXTRAINCDIRS += $(PORTINC)
EXTRAINCDIRS += $(KERNINC)
EXTRAINCDIRS += $(OSALINC)
EXTRAINCDIRS += $(STARTUPINC)
EXTRAINCDIRS += $(SHELLINC)

include $(CHIBIOS_DIR)/community/os/hal/hal.mk

CHIBIOS_VARIOUS_DIR := $(CHIBIOS_DIR)/os/various
CSRC += $(wildcard $(CHIBIOS_VARIOUS_DIR)/*.c)
EXTRAINCDIRS += $(CHIBIOS_VARIOUS_DIR)

CHIBIOS_STREAMS_DIR := $(CHIBIOS_DIR)/os/hal/lib/streams
CSRC += $(wildcard $(CHIBIOS_STREAMS_DIR)/*.c)
EXTRAINCDIRS += $(CHIBIOS_STREAMS_DIR)

include $(QHAL_DIR)/../library.mk
