
QOS_COMMON_PORTS_SIMIA32_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

PORTSRC += $(QOS_COMMON_PORTS_SIMIA32_DIR)/chcore.c

PORTASM += 

PORTINC += $(QOS_COMMON_PORTS_SIMIA32_DIR)

LDFLAGS += -T$(QOS_COMMON_PORTS_SIMIA32_DIR)/sections.ld
